---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
  selector:
    app: {{ .Release.Name }}
